apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-app-config
data:
  application.yml: |
    # Database Configuration
    spring:
      datasource:
        url: jdbc:mysql://localhost:3306/mydatabase
        username: myusername
        password: mypassword
        driver-class-name: com.mysql.cj.jdbc.Driver

    # Hibernate Configuration
    spring:
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
          ddl-auto: update

    # Server Configuration
    server:
      port: 8080

    # Logging Configuration
    logging:
      level:
        root: INFO
